version: '2'

services:
  klipper:
    # image: dimalo/klipper-moonraker
    # image: dimalo/klipper-moonraker:20230402-1347
    build:
      dockerfile: ./klipper/Dockerfile
      context: .
    # if klipper cannot connect to the printer check permissions on rpi then add the group here
    group_add:
      - "20"
      # - "998"
    cap_add:
      - SYS_NICE
    container_name: klipper
    ports:
      - 7125:7125
    restart: unless-stopped
    volumes:
      - /home/volumes/gcode_files:/home/klippy/printer_data/gcodes
      - /home/volumes/klipper-web/config:/home/klippy/printer_data/config
      - /home/volumes/moonraker_data:/home/klippy/printer_data
      # - /home/volumes/klipper-web/config:/home/klippy/.config
    devices:
      - /dev/serial/by-id/usb-Klipper_stm32f103xe_30FFD6054254353924701557-if00:/dev/serial/by-id/usb-Klipper_stm32f103xe_30FFD6054254353924701557-if00
      # - /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0:/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0

  fluidd:
    # image: dimalo/fluidd
    build:
      dockerfile: Dockerfile
      context: frontend
    restart: unless-stopped
    container_name: fluidd
    ports:
      - 8010:80
    depends_on: 
      - klipper
    links:
      - klipper:klipper
